version: '3.8'
name: rad

networks:
    ms-network:
        name: ms-network
        driver: bridge
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - ms-network
    volumes:
      - /mongodb_data:/data/db
  ms-api-gateway:
    image: yuvalroth123/rad-ms-api-gateway
    container_name: ms-api-gateway
    networks:
      - ms-network
    depends_on:
      - mongodb
  ms-nba:
    image: yuvalroth123/rad-ms-nba
    container_name: ms-nba
    env_file:
      - keys.env
    networks:
      - ms-network
    depends_on:
      - mongodb
  ms-news:
    image: yuvalroth123/rad-ms-news
    container_name: ms-news
    env_file:
      - keys.env
    networks:
        - ms-network
  ms-population:
    image: yuvalroth123/rad-ms-population
    container_name: ms-population
    depends_on:
      - mongodb
    env_file:
      - keys.env
    networks:
      - ms-network
  client-vaadin:
    image: yuvalroth123/rad-client-vaadin
    container_name: client-vaadin
    ports:
      - "80:80"
    networks:
      - ms-network
    depends_on:
      - ms-api-gateway
      - ms-nba
      - ms-news
      - ms-population
      - mongodb
