{
 "title": "micro_services",
 "time": { "from": "2024-06-23T15:52:39.751Z", "to": "2024-06-23T15:55:52.491Z" },
 "panels": [
  {
   "title": "process cpu",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "disk free bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "disk_free_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "services up",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Count for All Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[15m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}